### ISSUE TITLE
firebase credentials

### ISSUE THREAD

**Issue by mehmetkose** [instaflutter/flutter-walkthrough-onboarding-flow#1]
where should I put the firebase information? which file I mean.

**Comment by instamobile** [comment]
For android, replace android/app/google-services.json file with your own (download it from your Firebase Console). For iOS, replace ios/GoogleService-Info.plist file. I'll update the README to include this info. Thanks for trying out this project.

**Comment by mehmetkose** [comment]
for sure! I'm a newbie on flutter. thank you for this repository.
